name: Hardcore
version: @version@
api-version: '1.16'
main: com.xsota.hardcore.Hardcore
author: xsota
website: https://github.com/xsota/hardcore

commands:
  selfharm:
    description: This is a self harm command.
    usage: /<command>
    permission: xsotaHardcore.basic
    permission-message: You don\'t have <permission>

permissions:
  xsotaHardcore.*:
    description: Gives access to all commands
    children:
      xsotaHardcore.basic: true
  xsotaHardcore.basic:
    description: Gives access to basic commands
    default: true
